blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,include,re_path

app_name='blog'

urlpatterns = [
    url('^index/$', views.index,name='index'),
    re_path('^article/(?P<article_id>[0-9]+)$', views.article_page,name='article_page'),
    re_path('^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url('^edit/action/$', views.edit_action,name='edit_action'),
    url('^edit/del_action', views.del_action, name='del_action'),
]

blog2/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^index/$', views.index),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    url('^blog2/', include('blog2.urls'))
]

blog/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(null=True)
    pub_time=models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    article_id = request.POST.get('article_id', '0')
    print('=' * 30)
    print(article_id)
    print('=' * 30)
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')

    pub_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    if article_id == '0':
        models.Article.objects.create(title=title, content=content, pub_time=pub_time)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article': article})


def del_action(request):
    article_id = request.POST.get('article_id')
    print('=' * 30)
    print(article_id)
    print('=' * 30)
    models.Article.objects.filter(id=article_id).delete()
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'blog2/index.html')

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
    <style type="text/css">
        a{
            color: coral;
            text-decoration: none;
        }
    </style>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/>
<br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
<a href="{% url 'blog:index' %}">返回主页</a>
<p>
    创建时间：
</p>
<p>
    {{ article.pub_time | date:'Y-n-j G:i:s'}}
</p>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>
        <input type="hidden" name="article_pub_time" value="{{ article.pub_time | default:'0' }}"/>
        <label>
            文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br/>
        <label>
            文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br/>
    <input type="submit" value="提交">

</form>
<form action="{% url 'blog:del_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>
    <input type="submit" value="删除">
</form>

</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <link rel="stylesheet" href="{% static '/blog/index.css' %}">
{#    <style>#}
{#        h1{#}
{#            background: black;#}
{#            margin: 0;#}
{#        }#}
{#        h1 a{#}
{#            color: white;#}
{#            text-decoration: none;#}
{#        }#}
{#    </style>#}
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">发表博客</a>
</h1>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}:</a>
    <h4>

        &nbsp;&nbsp;{{ article.content }}
    </h4>
    <br/>
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello,blog2</h1>
</body>
</html>